name: Deploy collection
on:
  push:
    branches: [master, main, postman-collection]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: aanimesh23/openapi-publish-action@v1
        with:
          collectionName: Github actions collection test
          workspaceName: My Workspace
          postmanApiKey: ${{ secrets.POSTMAN_API_KEY }}
          openApiSpec: ./swagger.yaml
